name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "😁  ${{ github.event_name }} event ne  job start kar di hehe."
      - run: echo "🐧  ${{ runner.os }} server hosted by GitHub!,naya os layo yaar"
      - run: echo "🔎 tera branch ka nam ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "taiyar ho gyiii!!!🐧🐧🐧."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
